version: 2.1
jobs:
  compile:
    docker:
      - image: ubuntu:19.10
    steps:
      - run: apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget
      - run: git clone https://github.com/Mmhmdfas/android-kernel-xiaomi-msm8917 -b lineage-16.0 --depth=1 .
      - run: wget https://raw.githubusercontent.com/Mmhmdfas/script/master/circleci
      - run: chmod +x circleci
      - run: bash circleci
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
